version: 0.2
env: 
  parameter-store:
      DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
      DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
      DOCKER_REGISTRY_URL: /myapp/docker-credentials/url
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven..."
      - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
      - sudo mv epel-apache-maven.repo /etc/yum.repos.d/
      - sudo yum -y install apache-maven  
pre_build:
    commands:
      - echo "Installing dependencies..."
build:
    commands:
      - echo "Build started on `date`"
      - mvn clean install
      - echo "Build completed on `date`"
post_build:
    commands:
      - echo "running tests"
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sprint_boot_shopping:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sprint_boot_shopping:latest"
      - echo "Build completed successfully!"
artifacts:
  files:
    - target/*.jar
  discard-paths: yes      

